apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sample.name" . }}-ingress
  namespace: {{ .Values.nameSpace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/client-max-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: {{ .Values.ingress.host | default "openmodel.example.com" }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "sample.name" . }}
            port:
              number: {{ .Values.service.port }}
