apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample.name" . }}
  namespace: {{ .Values.nameSpace }}
  labels:
    {{- include "sample.labels" . | nindent 4 }}
  annotations:
  # Ensures Azure provisions a public load balancer
     #service.beta.kubernetes.io/azure-load-balancer-internal: "false"
    service.beta.kubernetes.io/azure-dns-label-name: "openmodel-api"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
  selector:
    {{- include "sample.selectorLabels" . | nindent 4 }}
